backend:
  name: git-gateway
  branch: main

media_folder: src/assets/images
public_folder: /assets/images

collections:
  - name: news
    label: News
    folder: src/news
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Body, name: body, widget: markdown }
